'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ChevronLeft,ChevronRight,X,Camera} from 'lucide-react';
import Logo from './Logo';
import type {Event,Photo} from '../lib/types';
export default function GalleryAlbum({id}:{id:string}){
 const [event,setEvent]=useState<Event|null>(null),[photos,setPhotos]=useState<Photo[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<number|null>(null);
 useEffect(()=>{let alive=true;fetch(`/api/albums/${encodeURIComponent(id)}`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error(r.status===404?'Album not found or not published.':'Unable to load album.');return r.json() as Promise<{event:Event;photos:Photo[]}>;}).then(data=>{if(alive){setEvent(data.event);setPhotos(data.photos);}}).catch(e=>{if(alive)setError(e.message||'Unable to load album.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[id]);
 useEffect(()=>{if(selected===null)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='ArrowRight')setSelected(i=>i===null?null:(i+1)%photos.length);if(e.key==='ArrowLeft')setSelected(i=>i===null?null:(i-1+photos.length)%photos.length);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[selected,photos.length]);
 return <><header className="site-header"><div className="header-inner"><a href="/" aria-label="House of Judah home"><Logo/></a><a href="/gallery" className="album-back"><ArrowLeft size={17}/> All events</a></div></header><main className="section album-page"><a href="/gallery" className="album-back"><ArrowLeft size={17}/> Back to all events</a>{loading?<p className="quiet-state">Loading album…</p>:error?<p className="notice" role="alert">{error}</p>:!event?<p className="quiet-state">Album not found or not published.</p>:<><p className="eyebrow">Moments together / Event album</p><h1>{event.title}</h1><p className="album-page-subtitle">{new Date(event.start_at).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Kolkata'})} · {event.venue} · {photos.length} photos</p>{event.description&&<p className="album-description">{event.description}</p>}{photos.length?<div className="album-masonry">{photos.map((p,i)=><button key={p.id} className="album-masonry-item" onClick={()=>setSelected(i)} aria-label={`Open photo ${i+1}`}><img src={`/api/media/${p.id}`} alt={p.caption||`${event.title} photo ${i+1}`} loading="lazy"/>{p.caption&&<span>{p.caption}</span>}</button>)}</div>:<div className="quiet-state"><Camera/><p>No photos have been published for this event yet.</p></div>}</> }</main>{selected!==null&&photos[selected]&&<div className="album-viewer" role="dialog" aria-modal="true" aria-label="Photo viewer" onClick={()=>setSelected(null)}><button className="album-viewer-close" aria-label="Close" onClick={()=>setSelected(null)}><X/></button><button className="album-viewer-prev" aria-label="Previous photo" onClick={e=>{e.stopPropagation();setSelected((selected-1+photos.length)%photos.length);}}><ChevronLeft/></button><img src={`/api/media/${photos[selected].id}`} alt={photos[selected].caption||'Event photo'} onClick={e=>e.stopPropagation()}/><button className="album-viewer-next" aria-label="Next photo" onClick={e=>{e.stopPropagation();setSelected((selected+1)%photos.length);}}><ChevronRight/></button><span className="album-viewer-caption">{selected+1} / {photos.length}{photos[selected].caption?` · ${photos[selected].caption}`:''}</span></div>}</>;
}
