'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CalendarDays,Camera,Music2,MapPin,Menu,X,ChevronLeft,ChevronRight,Heart,Mail,Disc3} from 'lucide-react';
import Logo from './Logo';
import ReleaseCard from './ReleaseCard';
import type {Event,Photo,Release} from '../lib/types';

type Content={events:Event[];photos:Photo[];releases:Release[]};
const formatDate=(s:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'long',year:'numeric'})=>new Intl.DateTimeFormat('en-IN',{...options,timeZone:'Asia/Kolkata'}).format(new Date(s));
export default function Site({initial,unavailable=false}:{initial:Content;unavailable?:boolean}){
  const [content,setContent]=useState(initial),[error,setError]=useState(unavailable),[menu,setMenu]=useState(false),[album,setAlbum]=useState('all'),[lightbox,setLightbox]=useState<number|null>(null),[now,setNow]=useState(Date.now());
  const [sending,setSending]=useState(false),[message,setMessage]=useState(''),[sent,setSent]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null);
  async function refresh(){try{const res=await Promise.all(['/api/events','/api/photos','/api/music'].map(u=>fetch(u,{cache:'no-store'})));if(res.some(r=>!r.ok))throw new Error();const [events,photos,releases]=await Promise.all(res.map(r=>r.json())) as [Event[],Photo[],Release[]];setContent({events,photos,releases});setError(false);setNow(Date.now());}catch{setError(true);}}
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);const onFocus=()=>{void refresh();};window.addEventListener('focus',onFocus);return()=>{clearInterval(timer);window.removeEventListener('focus',onFocus);};},[]);
  const upcoming=content.events.filter(e=>+new Date(e.end_at)>=now).sort((a,b)=>+new Date(a.start_at)-+new Date(b.start_at));
  const photos=content.photos.filter(p=>album==='all'||p.event_id===album);
  const albums=content.events.filter(e=>e.published && +new Date(e.end_at)<now && (e.photo_count||0)>0).sort((a,b)=>+new Date(b.start_at)-+new Date(a.start_at)).slice(0,6);
  useEffect(()=>{if(lightbox!==null&&!dialog.current?.open)dialog.current?.showModal();if(lightbox===null&&dialog.current?.open)dialog.current.close();},[lightbox]);
  function openPhoto(i:number){setLightbox(i);}
  async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setSending(true);setMessage('');setSent(false);try{const res=await fetch('/api/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||'Please try again.');setSent(true);setMessage('Your invitation has been received. Thank you for inviting us to worship with you.');form.reset();}catch(e){setMessage(e instanceof Error?e.message:'Your invitation could not be sent. Please try again.');}finally{setSending(false);}}
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><div className="header-inner"><a className="brand-link" href="#home" aria-label="House of Judah home"><Logo/></a><button className="mobile-menu" aria-expanded={menu} aria-controls="main-nav" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav id="main-nav" aria-label="Main navigation" className={menu?'is-open':''}>{[['About','#about'],['Music','#music'],['Events','#events'],['Gallery','/gallery'],['Team','#team']].map(([label,url])=><a href={url} key={url} onClick={()=>setMenu(false)}>{label}</a>)}<a className="button button-small" href="#invite" onClick={()=>setMenu(false)}>Book us</a></nav></div></header>
    <main id="main">
      <section id="home" className="hero"><div className="hero-inner"><h1 className="hero-title"><Logo large/></h1><p className="hero-description">United to praise, worship,<br className="desktop-break"/> and glorify God.</p><div className="hero-actions"><a className="button button-outline" href="#events"><CalendarDays size={17}/>Upcoming events</a></div><div className="hero-note"><span>Rooted in the Word.</span><span>Growing together in worship.</span></div></div></section>
      <section id="about" className="section about-section"><div className="section-label"><span className="eyebrow">Our story</span><span className="small-text">EST. 2025</span></div><div className="about-grid"><div><h2>Many beginnings.<br/>One heart for worship.</h2><p>House of Judah was established in 2025 by people from different colleges. As we became friends, we decided to start a band, bringing together our love for God and music.</p><p>After praying and meditating on God’s Word, we chose the name House of Judah. To us, it represents people united to praise, worship, and glorify God.</p><div className="first-event"><span className="eyebrow">Where it began</span><h3>Youth Christmas</h3><p>Our first event was at Shine of Shekinah Church, Madhapur, where we led praise and worship.</p></div></div><div className="verse-card"><span className="quote-mark" aria-hidden="true">“</span><blockquote>And the remnant that is escaped of the house of Judah shall again take root downward, and bear fruit upward.</blockquote><cite>Isaiah 37:31</cite><p>This promise reminds us that even after difficult times, God restores His people, strengthens their roots, and enables them to bear good fruit.</p></div></div>
      <div className="mission-block"><div><p className="eyebrow">Our vision & mission</p><h3>Rooted in Him.<br/>In every season.</h3></div><div><p>We are here to build the kingdom of God through praise and worship. Whatever our situation, we believe God never leaves us—and we want to remain faithful to Him.</p><p>David danced before the Lord. Even in our pain and struggles, we are invited to turn our hearts towards Him. Our joy is in <strong>Jesus.</strong></p></div></div>
      <div className="team-block"><div><p className="eyebrow">Serving together</p><h3>Our team</h3></div><div className="team-members"><div><span>President</span><h4>Ashish Daniel K</h4></div><div><span>Vice President</span><h4>Sahan Raj P</h4></div></div></div></section>
      <section id="music" className="section bordered"><p className="eyebrow">Songs of praise</p><h2>Latest Release</h2>{content.releases.length?<div className="music-grid">{content.releases.map(r=><ReleaseCard key={r.id} release={r}/>)}</div>:<div className="quiet-state"><Music2/><div><h3>Music brings us together.</h3><p>Watch our worship videos on YouTube and Instagram. New recordings and their thumbnails will appear here.</p></div></div>}</section>
      <section id="events" className="section bordered"><div className="section-heading"><div><p className="eyebrow">Gather with us</p><h2>Upcoming Events</h2></div><span className="small-text">All times · India Standard Time</span></div>{error&&<p className="notice" role="status">Events and photos could not be loaded. <button className="text-button" onClick={refresh}>Try again</button></p>}{upcoming.length?<div className="event-list">{upcoming.map(e=><details className="event-row" key={e.id}><summary><div className="event-date"><span>{formatDate(e.start_at,{month:'short'})}</span><strong>{formatDate(e.start_at,{day:'2-digit'})}</strong></div><div className="event-summary"><h3>{e.title}</h3><p><MapPin size={14}/>{e.venue}</p></div><span className="event-time">{formatDate(e.start_at,{hour:'numeric',minute:'2-digit'})}</span><span className="event-detail-label">Details +</span></summary><div className="event-details"><p>{e.description||'Join us for a time of praise and worship.'}</p><p>{formatDate(e.start_at)} · {formatDate(e.start_at,{hour:'numeric',minute:'2-digit'})} – {formatDate(e.end_at,{hour:'numeric',minute:'2-digit'})}</p>{e.registration_url&&<a className="button" href={e.registration_url} target="_blank" rel="noopener noreferrer">Register / book</a>}{e.cover_id&&<img src={`/api/media/${e.cover_id}`} alt={`${e.title} poster`} loading="lazy"/>}</div></details>)}</div>:<div className="quiet-state"><CalendarDays/><div><h3>Our next gathering is yet to be announced.</h3><p>Come back for upcoming events.</p></div><a className="text-button" href="#invite">Invite us to your church</a></div>}</section>
      <section id="gallery" className="section bordered"><div className="section-heading"><div><p className="eyebrow">Life in worship</p><h2>Moments together</h2></div><span className="small-text">The people. The praise. The memories.</span></div>{albums.length?<><div className="album-folder-grid">{albums.map(e=>{const cover=e.cover_id;return <a key={e.id} href={`/gallery/${encodeURIComponent(e.id)}`} className="album-folder"><div className="album-folder-cover">{cover?<img src={`/api/media/${cover}`} alt={`${e.title} album cover`} loading="lazy"/>:<Camera/>}<span className="album-folder-count">{e.photo_count||0} photos</span></div><div className="album-folder-info"><h3>{e.title}</h3><p>{formatDate(e.start_at)}</p></div></a>})}</div><div className="album-archive-action"><a className="button button-outline" href="/gallery">View all events →</a></div></>:<div className="quiet-state"><Camera/><div><h3>A place for our shared memories.</h3><p>Photos from our gatherings will appear here after each event.</p></div></div>}</section>
      <section id="team" className="section bordered"><p className="eyebrow">One heart. Many gifts.</p><h2>Meet our team</h2><p className="section-intro">Worship & Media</p><div className="people-grid">{[['Ashish Daniel K','Worship Leader • Lead Vocalist • Drummer'],['Sushanth Daggumati','Worship Leader • Lead Vocalist • Guitarist'],['Eric Judson','Lead Guitars'],['Ratnaraju Meesala','Bassist'],['Chandra Prakash D','Drummer'],['Sahan Raj P','Keyboardist'],['Prince Philomon B','Keyboardist'],['Vishal','Percussions'],['Samuel Anguluri','Media Head']].map(([name,role])=><article className="person" key={name}><h3>{name}</h3><p>{role}</p></article>)}</div></section>
      <section id="invite" className="section invite-section"><p className="eyebrow">Let’s worship together</p><h2>Book us</h2><p className="section-intro">Invite us to lead worship at your church, youth gathering, or event.</p><div className="booking-links"><a href="tel:+918985469202"><span>Call HOJ</span>8985469202</a><a href="mailto:houseofjudahhh@gmail.com"><span>Email</span>houseofjudahhh@gmail.com</a><a href="https://www.instagram.com/houseof.judah/" target="_blank" rel="noopener noreferrer"><span>Instagram</span>@houseof.judah</a></div><form className="invitation-form" onSubmit={invite}><div className="form-grid"><label>Your name<input name="name" autoComplete="name" required maxLength={120} placeholder="Your full name"/></label><label>Email address<input name="email" autoComplete="email" type="email" required maxLength={254} placeholder="you@example.com"/></label><label>Organization / church<input name="organization" autoComplete="organization" required maxLength={200} placeholder="Church or organization name"/></label><label>Event date<input name="eventDate" type="date" required/></label><label className="full-width">Tell us about your event<textarea name="message" required rows={4} maxLength={3000} placeholder="Location, timings, and anything you would like us to know…"/></label></div><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button className="button full-width" disabled={sending}>{sending?'Sending…':'Send invitation'}</button>{message&&<p className={`form-message ${sent?'success':''}`} role="status">{message}</p>}</form></section>
    </main>
    <footer className="site-footer"><div className="footer-inner"><a href="#home" aria-label="House of Judah home"><Logo/></a><p>United to praise, worship, and glorify God.</p><div className="footer-socials"><a href="https://www.instagram.com/houseof.judah/" target="_blank" rel="noopener noreferrer">Instagram</a><a href="mailto:houseofjudahhh@gmail.com">Contact</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} House of Judah</span><span>Rooted in faith. Growing in worship.</span></div></footer>
    <dialog ref={dialog} className="lightbox" onCancel={()=>setLightbox(null)} onClick={e=>{if(e.target===dialog.current)setLightbox(null);}} onKeyDown={e=>{if(lightbox===null)return;if(e.key==='ArrowRight')setLightbox((lightbox+1)%photos.length);if(e.key==='ArrowLeft')setLightbox((lightbox-1+photos.length)%photos.length);}}><button className="lightbox-close" onClick={()=>setLightbox(null)} aria-label="Close photo"><X/></button>{lightbox!==null&&photos[lightbox]&&<><img src={`/api/media/${photos[lightbox].id}`} alt={photos[lightbox].caption||photos[lightbox].event_title}/><div className="lightbox-bottom"><button disabled={photos.length<2} aria-label="Previous photo" onClick={()=>setLightbox((lightbox-1+photos.length)%photos.length)}><ChevronLeft/></button><p>{photos[lightbox].caption||photos[lightbox].event_title}<span>{lightbox+1} / {photos.length}</span></p><button disabled={photos.length<2} aria-label="Next photo" onClick={()=>setLightbox((lightbox+1)%photos.length)}><ChevronRight/></button></div></>}</dialog>
  </>;
}
