import {admin,bucket,db,fail,getPhotos,noStore,textValue} from '../../lib/store';
export async function GET(r:Request){try{const all=new URL(r.url).searchParams.get('admin')==='1';if(all){const denied=await admin();if(denied)return denied;}return Response.json(await getPhotos(all),{headers:noStore});}catch(e){return fail(e);}}
export async function POST(r:Request){const denied=await admin(r);if(denied)return denied;try{
if(Number(r.headers.get('content-length')||0)>11*1024*1024)return Response.json({error:'Choose a photo smaller than 10 MB.'},{status:413});
const f=await r.formData(),file=f.get('photo'),eventId=textValue(f.get('eventId'),80),caption=textValue(f.get('caption'),300),kind=f.get('kind')==='poster'?'poster':'photo',replaceId=textValue(f.get('replaceId'),80);
const event=await db().prepare('SELECT id,poster_id FROM events WHERE id=? AND deleted=0').bind(eventId).first<{id:string;poster_id:string|null}>();if(!event)return Response.json({error:'Save an event before adding photos.'},{status:400});
const replace=replaceId?await db().prepare('SELECT id,storage_key,caption,kind FROM photos WHERE id=? AND event_id=? AND deleted=0').bind(replaceId,eventId).first<{id:string;storage_key:string;caption:string;kind:string}>():null;if(replaceId&&!replace)return Response.json({error:'Photo to replace was not found.'},{status:404});
if(!(file instanceof File)||!file.size||file.size>10*1024*1024)return Response.json({error:'Choose a JPG, PNG, or WebP photo up to 10 MB.'},{status:400});

const n=await db().prepare('SELECT COUNT(*) AS n FROM photos WHERE event_id=? AND deleted=0').bind(eventId).first<{n:number}>();if(!replaceId&&kind!=='poster'&&(n?.n||0)>=100)return Response.json({error:'This album has reached its 100-photo limit.'},{status:400});
const bytes=new Uint8Array(await file.arrayBuffer());let mime='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime='image/jpeg';else if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10)mime='image/png';else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')mime='image/webp';
if(!mime)return Response.json({error:'This is not a supported photo. Use JPG, PNG, or WebP.'},{status:400});
const id=crypto.randomUUID(),key=`photos/${id}`;await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});try{const actualKind=replace?.kind||kind;const ops=[db().prepare('INSERT INTO photos (id,event_id,storage_key,mime,size,caption,kind,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,eventId,key,mime,file.size,replace?.caption||caption,actualKind,new Date().toISOString())];if(actualKind==='poster'){ops.push(db().prepare('UPDATE events SET poster_id=? WHERE id=?').bind(id,eventId));if(event.poster_id)ops.push(db().prepare('UPDATE photos SET deleted=1 WHERE id=?').bind(event.poster_id));}if(replaceId)ops.push(db().prepare('UPDATE photos SET deleted=1 WHERE id=?').bind(replaceId));await db().batch(ops);}catch(e){await bucket().delete(key);throw e;}
return Response.json({id},{status:201,headers:noStore});}catch(e){return fail(e);}}
